name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '* * * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: 23df3c6e-2e17-41f4-bedc-d01716049fb5
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
